name: ccl_services
description: "CeylonCodeLabs Service Extensions"
version: 0.6.1
homepage: https://github.com/CeylonCodeLabs/ccl_packages

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ccl_core: '>=0.2.0'
  stacked: '>=3.4.2 <4.0.0'
  stacked_services: ^1.6.0
  flutter_secure_storage: ^9.2.2
  rxdart: ^0.28.0
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  uuid: ^4.5.1

## for development only
#dependencies:
#  flutter:
#    sdk: flutter
#  ccl_core:
#    path: '../ccl_core'
#  stacked: '>=3.4.2 <4.0.0'
#  stacked_services: ^1.5.0
#  flutter_secure_storage: ^9.2.2
#  rxdart: ^0.28.0
#  intl: ^0.19.0
#  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

scripts:
  gen_docs: git-chglog -o CHANGELOG.md && git log --pretty="- %s (%an)" $(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))..HEAD > release_note.txt