name: ccl_services
description: "CeylonCodeLabs Service Extensions"
version: 0.2.5
homepage: https://github.com/CeylonCodeLabs/ccl_packages

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_support_pack: '>=1.4.1 <2.0.0'
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  flutter_secure_storage: ^9.2.2
  rxdart: ^0.27.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


scripts:
  gen_changelog: git-chglog -o CHANGELOG.md
  gen_release_note: git log --pretty="- %s (%an)" $(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))..HEAD > release_note.txt